unet:
  n_blocks: 4
  n_layers_per_block: 3
  n_first_block_channels: 8
  _activation: "new_gelu"
  ln_eps: 1e-5
  device: "cuda"
  _dtype: "float16"

discriminator:
  n_blocks: 4
  n_layers_per_block: 3
  n_first_block_channels: 8
  _activation: "new_gelu"
  ln_eps: 1e-5
  device: "cuda"
  _dtype: "float16"
  loss_eps: 1e-4

optimizer:
  _optimizer: "adamw"
  lr: 1e-4
  weight_decay: 5e-2
  lr_schedule: "invsqrt"
  adam_eps: 1e-4
  beta1: 0.9
  beta2: 0.999
  warmup_iters: 1_000
  max_iters: 50_000
  init_std: 2e-2
  batch_size: 16

source_files_path: "/home/kanhar/workspace/gans/pytorch-deepdream/wider/images"
processed_files_path: "/home/kanhar/workspace/gans/pytorch-deepdream/data/out-images/RESNET50_IMAGENET/"
eval_interval: 200
eval_iters: 25
log_interval: 10
wandb_log: true
wandb_run_name: "first-run"
compile_model: false
image_size: 256
